# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "waprin"

# URL
baseurl:            https://waprin.io
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

title: Bill Prin's Personal Page

tagline: Bill  Prin's Technical Blog

description: This is the technical blog and about page for Bill Prin aka William Prin

url: https://waprin.io

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Blog"
    href:           "/blog"
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

author: 
  twitter: "waprin_io"
  github : waprin
  linkedin: waprin
  stackoverflow: 226773
  medium: waprin
  soundcloud: metawish

plugins:
  - jekyll-seo-tag