# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "billprin"

# URL
#baseurl:            https://waprin.io
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

title: Bill Prin's Tech Blog

tagline: Bill  Prin's Tech Blog

description: Bill Prin's Tech Blog

url: https://billprin.com

# Navigation
nav:
  - name:           "Home"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

author: 
  twitter: "bill_prin"
  github : waprin
  linkedin: waprin
  stackoverflow: 226773
  medium: waprin
  picture: "assets/waprin_profile.jpg"
  name: "Bill Prin"

plugins:
  - jekyll-seo-tag